In [1]:
# TODO: remember about preemphasis/deemphasis!
import numpy as np
import os
from lpc.coding import Encoder
from lpc.utils import get_audio

fs = 44100
bt_min_f, bt_max_f = 50, 400
encoder = Encoder(240, 180, 50, 400)
decoder = Decoder(180)

In [2]:
audio_dir = os.path.join('.', '..', 'audio')

audio = get_audio(os.path.join(audio_dir, 'a.wav'))
left = audio[:, 0].astype(np.double)

In [5]:
enc = encoder.encode(left, fs)
dec = d

[array([ 0.        , -0.89636833, -0.10759159, -0.07485694,  0.23252113,
        -0.26679976,  0.16444477, -0.14818375,  0.08404776,  0.03160768,
        -0.0038376 ,  0.25997892]),
 array([ 0.00249433, -0.96406146, -0.11375462,  0.05647553,  0.35125481,
        -0.43714106,  0.07413741, -0.16608537,  0.11657914, -0.06748749,
         0.17614254,  0.35843678]),
 array([ 0.        , -0.86602494, -0.19305713,  0.05177131,  0.15866968,
        -0.3101624 ,  0.14120151, -0.1147837 ,  0.06234875, -0.08724302,
         0.17290571,  0.40965069]),
 array([ 0.        , -1.15608912,  0.12410819,  0.18115415,  0.12995709,
        -0.43625581,  0.11183924, -0.09176212,  0.07756338, -0.18132845,
         0.26428506,  0.47676647]),
 array([ 0.        , -1.00098416, -0.08471606,  0.11380588,  0.21685067,
        -0.31722057,  0.07896644, -0.17199671,  0.03269831,  0.02810603,
         0.12513101,  0.54381787]),
 array([ 0.        , -1.23277292,  0.18317356,  0.21132089,  0.05543119,
        -0.481484