In [1]:
# TODO: remember about preemphasis/deemphasis!
import numpy as np
import os
from lpc.coding import Encoder
from lpc.utils import get_audio

fs = 44100
bt_min_f, bt_max_f = 50, 400
encoder = Encoder(240, 180, 50, 400)

In [2]:
audio_dir = os.path.join('.', '..', 'audio')

audio = get_audio(os.path.join(audio_dir, 'a.wav'))
left = audio[:, 0].astype(np.double)
enc = encoder.encode(left, fs)

In [5]:
list(enc)

[array([1.1723356e-002, 1.8972121e-321]),
 array([7.64172336e-003, 4.68891661e-310]),
 array([0.00000000e+000, 4.68891661e-310]),
 array([0.00000000e+000, 4.68891661e-310]),
 array([0.00000000e+000, 6.93116221e-310]),
 array([0., 0.]),
 array([0.0e+000, 1.4e-322]),
 array([0.00000000e+000, 4.24399158e-314]),
 array([0.00000000e+000, 1.27319747e-313]),
 array([0.00000000e+000, 4.68891661e-310]),
 array([0.00000000e+000, 6.36598737e-314]),
 array([0.e+000, 1.e-323]),
 array([0.00000000e+000, 4.68891661e-310]),
 array([0.00000000e+000, 6.93116229e-310]),
 array([0.00000000e+000, 3.39519327e-313]),
 array([0.0000000e+000, 4.6887619e-310]),
 array([0.00000000e+000, 4.24399158e-314]),
 array([0.00000000e+000, 5.72938864e-313]),
 array([0., 0.]),
 array([0.00000000e+000, 4.68891661e-310]),
 array([0.00000000e+000, 4.68891661e-310]),
 array([0.e+000, 3.e-323]),
 array([0.00000000e+000, 4.68891661e-310]),
 array([0.00000000e+000, 1.48539705e-313]),
 array([0.0e+000, 2.5e-323]),
 array([0.000000